version: '3'
services:
     db:
             restart: always
             image: mysql:8.0
             container_name: my_mysql
             volumes:
                     - ./mysql_data:/var/lib/mysql
                     - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
             environment:
                     - "MYSQL_ROOT_PASSWORD=czy-root"
                     - "MYSQL_DATABASE=blog"
                     - "MYSQL_USER=czyblog"
                     - "MYSQL_PASSWORD=czy"
                     - "TZ=Asia/Shanghai"
             networks:
                     - myBlog
             ports:
                     - 3306:3306
     redis:
             restart: always
             image: redis 
             container_name: docker_redis
             command: redis-server
             volumes:
                     - ./redis_data:/data
                     - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf
                       #                     - ./redis_conf/:/usr/local/etc/redis/
                     - ./redis_logs:/logs
             networks:
                     - myBlog
             ports:
                     - 6666:6379
     blog:
             restart: always
             image: czyblog:1.0
             container_name: blog
             ports:
                     - 8080:8081
             volumes:
                     -       ./log/blog-dev.log:/log/blog-dev.log
             networks:
                     - myBlog



networks:
        myBlog:
                driver: bridge




















